kversion: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "-u", "admin", "-p", "password", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-app
    environment:
      - NODE_ENV=docker
      - MONGO_URI=mongodb://admin:password@mongodb:27017/online_exam_db
    ports:
      - 5000:5000
    depends_on:
      - mongodb

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    environment:
      - NODE_ENV=docker
      - REACT_APP_API_BASE_URL=http://backend:5000
    ports:
      - 3100:3000
    depends_on:
      - backend

  user-frontend:
    build:
      context: user-portal-frontend
      dockerfile: Dockerfile
    container_name: user-frontend-app
    environment:
      - NODE_ENV=docker
      - REACT_APP_API_BASE_URL=http://backend:5000
    ports:
      - 3200:3000
    depends_on:
      - backend
      - frontend

volumes:
  mongo-data:
    driver: local

